### ISSUE TITLE
[BUG] F2 Mode doesn't work as expected

### ISSUE THREAD

**Issue by nvh0412** [nguyenquangminh0711/ruby_jard#10]
**Describe the bug**
F2 - mode didn't work as I expected 

**To Reproduce**
1. Go to 'rails console'
2. See all systems and application variables in variables panel
3. Click F2 to switch mode
4. Nothing happened

**Expected behavior**
The variables should be updated to show only application variables

**Screenshots**
<img width="1680" alt="Screen Shot 2020-08-03 at 10 05 34" src="https://user-images.githubusercontent.com/1973623/89142170-e1d35b80-d570-11ea-88f5-cadebacb3a41.png">

**Environment (please complete the following information):**
 - OS: MacOS Catalina
 - Terminal Emulator: Tmux + Iterm2
- Do you use tmux/screen or similar tty multiplexer? tmux

**Comment by nguyenquangminh0711** [comment]
Thanks for your reporting. F2 mode is currently under development in the master branch. So, the key binding won't work (for now). I'll update this when next version is released ❤️

**Comment by nguyenquangminh0711** [comment]
This issue is fixed via https://github.com/nguyenquangminh0711/ruby_jard/pull/28. The code is already in master. You can check it out. I'm batching the code, and do final tests before a new release :smiley:
