### ISSUE TITLE
[BUG] - binding.pry

### ISSUE THREAD

**Issue by scottbarrow** [nguyenquangminh0711/ruby_jard#39]
**Describe the bug**
Expected binding.pry to work as it does with pry, pry-rails, pry-debugger since pry is a dependency of this gem. 
It would be great if Jard was backwards compatible so that users who prefer binding.pry can use it alongside other team members wishing to use Jard

**To Reproduce**
1. Use binding.pry in a file

**Expected behavior**
Pry to work as it previously did

**Screenshots**
```
before_session hook failed: UncaughtThrowError: uncaught throw :jard_control_flow
/Users/scott/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby_jard-c794d14072ed/lib/ruby_jard/control_flow.rb:53:in `throw'
```

**Comment by nguyenquangminh0711** [comment]
This issue is fixed in https://github.com/nguyenquangminh0711/ruby_jard/pull/41. You can now use *one of* `binding.pry`, `byebug`, `debugger`, `jard` commands depending your preference. The limitation is that after `jard` is first triggered, the backward compatibility is not guranteed anymore. 

```ruby
def test
  jard
  sleep 0
  byebug # It triggers jard interfaces
  sleep 0
  binding.pry # Broken
end
```
