### ISSUE TITLE
[BUG] - Resizing terminal window breaks layout

### ISSUE THREAD

**Issue by scottbarrow** [nguyenquangminh0711/ruby_jard#40]
**Describe the bug**
When resizing the terminal window the layout breaks

**To Reproduce**
1. add jard toa. file
2. resize terminal window

**Expected behavior**
Layout to adjust with the window

**Screenshots**
![Screen Shot 2020-09-14 at 9 33 45 AM](https://user-images.githubusercontent.com/5571736/93113320-e6118f00-f66d-11ea-99f3-95aa3954065c.png)

**Comment by nguyenquangminh0711** [comment]
In previous versions, Jard used to auto-resize when the window changes. However, it has to refresh the whole window, and clear everything you are typing during resize event. That's kinda limited. So, I removed that feature to look for a better one. To make Jard resize perfectly, it must be aware of the current scroll position, able to control upward and downward scrolling, etc. I didn't found any solution for now :sweat:.
However, I agree that this layout broken is annoying. I think that we can accept the limitation and bring that feature back.

**Comment by nguyenquangminh0711** [comment]
This issue is fixed in https://github.com/nguyenquangminh0711/ruby_jard/pull/42. Once again, thank for reporting so many bugs :pray:
