### ISSUE TITLE
[BUG] Error on app startup -1 out of range

### ISSUE THREAD

**Issue by acetinick** [nguyenquangminh0711/ruby_jard#53]
**Describe the bug**
Stacktrace error as soon as application is starting, 

Using the master branch, still having same issues.

**To Reproduce**
on startup

**Screenshots**

 --- Error ---
web_1            | 17:05:09 web.1               | Internal error from Jard. I'm sorry to mess up your debugging experience.
web_1            | 17:05:09 web.1               | It would be great if you can submit an issue in https://github.com/nguyenquangminh0711/ruby_jard/issues
web_1            | 17:05:09 web.1               | 
web_1            | 17:05:09 web.1               | -2..-1 out of range
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/row_renderer.rb:75:in `[]='
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/row_renderer.rb:75:in `render_span'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/row_renderer.rb:33:in `block (2 levels) in render'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/row_renderer.rb:32:in `each'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/row_renderer.rb:32:in `block in render'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/row_renderer.rb:25:in `each'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/row_renderer.rb:25:in `render'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_renderer.rb:146:in `row_content'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_renderer.rb:105:in `block in find_seleted_window'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_renderer.rb:104:in `each'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_renderer.rb:104:in `each_with_index'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_renderer.rb:104:in `find_seleted_window'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_renderer.rb:97:in `calculate_window'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_renderer.rb:18:in `render'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_manager.rb:172:in `render_screen'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_manager.rb:147:in `block in build_screens'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_manager.rb:143:in `map'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_manager.rb:143:in `build_screens'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/screen_manager.rb:85:in `draw_screens'
web_1            | 17:05:09 web.1               | /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `draw_screens'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_processor.rb:66:in `process_commands'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_processor.rb:59:in `block (2 levels) in process_commands_with_lock'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/session.rb:163:in `block in lock'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/session.rb:162:in `synchronize'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/session.rb:162:in `lock'
web_1            | 17:05:09 web.1               | /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `lock'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_processor.rb:52:in `block in process_commands_with_lock'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/byebug-11.1.3/lib/byebug/helpers/eval.rb:94:in `allowing_other_threads'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_processor.rb:51:in `process_commands_with_lock'
web_1            | 17:05:09 web.1               | /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_processor.rb:37:in `at_line'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/byebug-11.1.3/lib/byebug/context.rb:98:in `at_line'
web_1            | 17:05:09 web.1               | /usr/src/app/app/controllers/employees_controller.rb:290:in `leave'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:195:in `process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/sentry-raven-3.1.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `instance_exec'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:139:in `run_callbacks'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/appsignal-2.11.0/lib/appsignal/hooks/active_support_notifications.rb:21:in `block in instrument'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/appsignal-2.11.0/lib/appsignal/hooks/active_support_notifications.rb:35:in `instrument'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/appsignal-2.11.0/lib/appsignal/hooks/active_support_notifications.rb:20:in `instrument'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/searchkick-4.4.1/lib/searchkick/logging.rb:212:in `process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activerecord-6.0.3.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:136:in `process'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:39:in `process'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:190:in `dispatch'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:254:in `dispatch'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:49:in `block in serve'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `each'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `serve'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:834:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/bullet-6.1.0/lib/bullet/rack.rb:15:in `call'
web_1            | 17:05:09 web.1               | /usr/src/app/config/application.rb:46:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/remotipart-1.4.4/lib/remotipart/middleware.rb:32:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/cookies.rb:648:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:567:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:101:in `run_callbacks'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/appsignal-2.11.0/lib/appsignal/rack/rails_instrumentation.rb:32:in `call_with_appsignal_monitoring'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/appsignal-2.11.0/lib/appsignal/rack/rails_instrumentation.rb:17:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/better_errors-2.8.1/lib/better_errors/middleware.rb:87:in `protected_app_call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/better_errors-2.8.1/lib/better_errors/middleware.rb:82:in `better_errors_call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/better_errors-2.8.1/lib/better_errors/middleware.rb:60:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/web-console-4.0.4/lib/web_console/middleware.rb:132:in `call_app'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/web-console-4.0.4/lib/web_console/middleware.rb:19:in `block in call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/web-console-4.0.4/lib/web_console/middleware.rb:17:in `catch'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:37:in `call_app'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `block in call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `block in tagged'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:28:in `tagged'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `tagged'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/static.rb:126:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/sentry-raven-3.1.0/lib/raven/integrations/rack.rb:51:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-mini-profiler-2.1.0/lib/mini_profiler/profiler.rb:357:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/puma-5.0.0/lib/puma/configuration.rb:238:in `call'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/puma-5.0.0/lib/puma/server.rb:620:in `handle_request'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/puma-5.0.0/lib/puma/server.rb:377:in `process_client'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/puma-5.0.0/lib/puma/server.rb:231:in `block in run'
web_1            | 17:05:09 web.1               | /usr/local/bundle/gems/puma-5.0.0/lib/puma/thread_pool.rb:141:in `block in spawn_thread'
web_1            | 17:05:09 web.1               | -------------
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
web_1            | 17:05:09 web.1               | EOFError: end of file reached
web_1            | 17:05:09 web.1               |   <internal:prelude>:73:in `__read_nonblock'
web_1            | 17:05:09 web.1               |   <internal:prelude>:73:in `read_nonblock'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/console.rb:93:in `getch'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_proxy.rb:196:in `read_key'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_proxy.rb:238:in `block (2 levels) in listen_key_press'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/key_bindings.rb:40:in `block in match'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/key_bindings.rb:39:in `loop'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/key_bindings.rb:39:in `match'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_proxy.rb:238:in `block in listen_key_press'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_proxy.rb:231:in `loop'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_proxy.rb:231:in `listen_key_press'
web_1            | 17:05:09 web.1               |   /usr/local/bundle/bundler/gems/ruby_jard-f3dc5a3f333e/lib/ruby_jard/repl_proxy.rb:171:in `block in repl'
web_1            | 17:05:09 log.1               | Completed 401 Unauthorized in 818ms (ActiveRecord: 35.3ms | Allocations: 284496)
web_1            | 17:05:09 log.1               | 
web_1            | 17:05:09 log.1               | 
web_1            | 17:05:11 web.1               | exited with code 1
web_1            | 17:05:11 system              | sending SIGTERM to all processes
web_1            | 17:05:11 worker_default.1    | 2020-09-19T17:05:11.224Z pid=8 tid=go5qdq9us INFO: Shutting down
web_1            | 17:05:11 worker_default.1    | 2020-09-19T17:05:11.224Z pid=8 tid=go5qdq9us INFO: Terminating quiet workers
web_1            | 17:05:11 worker_default.1    | 2020-09-19T17:05:11.224Z pid=8 tid=go5s2kzfs INFO: Scheduler exiting...
web_1            | 17:05:11 worker_converters.1 | 2020-09-19T17:05:11.227Z pid=10 tid=gpg5zh1mi INFO: Shutting down
web_1            | 17:05:11 worker_converters.1 | 2020-09-19T17:05:11.227Z pid=10 tid=gpg5zh1mi INFO: Terminating quiet workers
web_1            | 17:05:11 worker_converters.1 | 2020-09-19T17:05:11.228Z pid=10 tid=gpg7o9nim INFO: Scheduler exiting...
web_1            | 17:05:11 webpacker.1         | exited with code 0
web_1            | 17:05:11 log.1               | terminated by SIGTERM
web_1            | 17:05:11 worker_default.1    | 2020-09-19T17:05:11.726Z pid=8 tid=go5qdq9us INFO: Bye!
web_1            | 17:05:11 worker_converters.1 | 2020-09-19T17:05:11.729Z pid=10 tid=gpg5zh1mi INFO: Bye!
web_1            | 17:05:11 worker_default.1    | exited with code 0
web_1            | 17:05:11 worker_converters.1 | exited with code 0

**Environment (please complete the following information):**
 - docker 
- foreman
- rails 6.0.3.2
- ruby 2.6.6

**Comment by nguyenquangminh0711** [comment]
Hi @acetinick, thanks for reporting. Could I have some questions for clarifiation: 
- Are you running foreman inside Docker?
- Are you running docker with `docker-compose`, or plain docker?
- Did you put a `-it` option when running with `docker`? Or `tty: true` and `stdin_open: true` when running with `docker-compose`?

**Comment by acetinick** [comment]
hi @nguyenquangminh0711 , 

- yes, using docker and docker compose
- didn't put those options, but added it to docker-compose and still get same issue once the code hits the "jard" line.

![image](https://user-images.githubusercontent.com/571649/93707028-2ec8bc80-fb34-11ea-8290-c9a57bedfbaf.png)

**Comment by nguyenquangminh0711** [comment]
Hi @acetinick, sorry my bad, `tty: true`, and `stdin_open: true` are ignored when you run `docker-compose up`. When you run `docker-compose up`, that command is not meant to be interactive). See more at https://github.com/docker/compose/issues/3081.

I would suggest to do change your workflow a little bit:
- Use `docker-compose run`. For example: `docker-compose run --service-ports web`.  (Tested on my local)
- Start a blank container, and use `docker exec -it`. 
- Use `docker-compose up -d`. Then `docker ps`. Then `docker attach yourapp_web_1` for example. (Tested on my local)

Thanks for your reporting, but I'm afraid that Jard could not do anything about it (although it should display a more friendly error message).
