### ISSUE TITLE
Supporting "disable-pry" kind of functionality

### ISSUE THREAD

**Issue by kikonen** [nguyenquangminh0711/ruby_jard#58]
With pry, I've used following logic to allow resuming rails app, basically to resume from the loop. I.e. when rendering some long table and having breakpoint inside renderer, then just plain "continue" hits breakpoint on every iteration, but this trick have allowed to resume app and let it render page into end.

```
Pry::Commands.block_command "ec", "Continue from binding.pry" do |x, y, z|
  # @see https://stackoverflow.com/questions/8015531/how-do-i-step-out-of-a-loop-with-ruby-pry
  Pry::Commands.process_line String.new('disable-pry'), context
end
```

Problem is that with "jard", this causes this instead
```
{
  "exception_name": "SystemExit",
  "message": "exit",
  "inspect": "#<SystemExit: exit>",
  "drt_stacktrace": [
    "/gems/ruby-2.6.6@drt_ui/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/repl_processor.rb:145:in `exit'",
    "/gems/ruby-2.6.6@drt_ui/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/repl_processor.rb:145:in `handle_exit_command'",
    "/gems/ruby-2.6.6@drt_ui/bundler/gems/ruby_jard-cbba19ba3354/lib/ruby_jard/repl_processor.rb:87:in `handle_flow'",
    "    ... skipped 10 ...",
    "/gems/ruby-2.6.6@drt_ui/gems/byebug-11.1.3/lib/byebug/context.rb:98:in `at_line'",
   ...
```
thus internal error.

**Comment by nguyenquangminh0711** [comment]
Ah. The debugging functionality (stopping at a line) is powered by `byebug`, not pry. So, even if you disable pry, byebug still definitely stops at the next breakpoint though. I agree that this use case is common. 

I would like to suggest a new command: `skip` and friends

```
jard >> skip --help
Continue the execution, skip the first [times] breakpoint it encounters. This command is useful in cases when you placed `jard` into a loop, recursive, or nested method calls. 

Usage
  skip
  skip 3
``` 

There are more additional use cases that need to consider

```
jard >> continue --skip # Exactly the same as `skip`
jard >> step-out --skip # Step out of a frame, and skip any `jard` attachment in the middle. 
jard >> next --skip # Next over the next line, and skip any `jard` attachment in the middle
```

**Comment by nguyenquangminh0711** [comment]
Hi @kikonen, this feature is implemented and merged into master. You can read the instruction on the website (https://rubyjard.org/docs/commands/skip). You can try the fix at master branch first. I'll push a relase soon. Thanks for requesting this feature :heart: 

```ruby
gem 'ruby_jard', git: 'https://github.com/nguyenquangminh0711/ruby_jard', ref: 'master'
```
